### ISSUE TITLE
MovieAboutCreator doesn't work with MovieMeter anymore (API change ?)

### ISSUE THREAD

**Issue by Psymania** [SiWoC/MovieAboutCreator#1]
It seams the API with Moviemeter is broken, i can;t get any info or folder images from moviemeter anymore

**Comment by Psymania** [comment]
Hmm, seems to be related to some movies.....

**Comment by SiWoC** [comment]
Nice to see somebody is using my project, thanks.
If you post the movie-names you have problems with, maybe I can have a look too why Moviemeter doesn't return any info.
I also have some movies which the api just won't return like for example "1917 (2019)"

**Comment by Psymania** [comment]
Just checked, and the movies don't (yet) exist on Moviemeter at all:
- Around The Sun (2019)
- BraveStorm (2017)
- Dragon Soldiers (2020)
- Variant (2020)

P.S.
Also sometimes i don't get any folder info or background image at all, what i do is download a custom jpeg, name if folder.jpg or background.jpg, add them to the MAC generate folder and set them to readonly and then regenerate the about. 

Maybe an extra feature to add your own folder.jpg or background.jpg 👍
